export interface SpriteMetadata {
  displayName?: string
  spawns?: number
  isGenerator?: boolean
}

const SPRITE_METADATA: Record<number, SpriteMetadata> = {
  // Koopas (0x00-0x0D)
  0x00: { displayName: 'Green Koopa (no shell)' },
  0x01: { displayName: 'Red Koopa (no shell)' },
  0x02: { displayName: 'Blue Koopa (no shell)' },
  0x03: { displayName: 'Yellow Koopa (no shell)' },
  0x04: { displayName: 'Green Koopa' },
  0x05: { displayName: 'Red Koopa' },
  0x06: { displayName: 'Blue Koopa' },
  0x07: { displayName: 'Yellow Koopa' },
  0x08: { displayName: 'Green Para-Koopa (left)' },
  0x09: { displayName: 'Green Para-Koopa (bouncing)' },
  0x0a: { displayName: 'Red Para-Koopa (vertical)' },
  0x0b: { displayName: 'Red Para-Koopa (horizontal)' },
  0x0c: { displayName: 'Yellow Para-Koopa' },
  0x0d: { displayName: 'Bob-omb' },
  0x0e: { displayName: 'Keyhole' },
  0x0f: { displayName: 'Goomba' },
  0x10: { displayName: 'Para-Goomba (bouncing)' },
  0x11: { displayName: 'Buzzy Beetle' },
  0x12: { displayName: 'Unused (0x12)' },
  0x13: { displayName: 'Spiny' },
  0x14: { displayName: 'Spiny Egg (falling)' },
  0x15: { displayName: 'Cheep-Cheep (horizontal)' },
  0x16: { displayName: 'Cheep-Cheep (vertical)' },
  0x17: { displayName: 'Cheep-Cheep (from generator)' },
  0x18: { displayName: 'Jumping Cheep-Cheep' },
  0x19: { displayName: 'Message Box' },
  0x1a: { displayName: 'Piranha Plant (classic)' },
  0x1b: { displayName: 'Football (bouncing)' },
  0x1c: { displayName: 'Bullet Bill' },
  0x1d: { displayName: 'Hopping Flame' },
  0x1e: { displayName: 'Lakitu' },
  0x1f: { displayName: 'Magikoopa' },
  0x20: { displayName: "Magikoopa's Magic" },
  0x21: { displayName: 'Moving Coin' },
  0x22: { displayName: 'Green Net Koopa (vertical)' },
  0x23: { displayName: 'Red Net Koopa (vertical)' },
  0x24: { displayName: 'Green Net Koopa (horizontal)' },
  0x25: { displayName: 'Red Net Koopa (horizontal)' },
  0x26: { displayName: 'Thwomp' },
  0x27: { displayName: 'Thwimp' },
  0x28: { displayName: 'Blue Shell' },
  0x29: { displayName: 'Spike Top (counter-clockwise)' },
  0x2a: { displayName: 'Piranha Plant (upside-down)' },
  0x2b: { displayName: "Sumo Brother's Lightning" },
  0x2c: { displayName: 'Yoshi Egg' },
  0x2d: { displayName: 'Baby Yoshi (green)' },
  0x2e: { displayName: 'Spike Top' },
  0x2f: { displayName: 'Springboard (portable)' },
  0x30: { displayName: 'Dry Bones (throws bones)' },
  0x31: { displayName: 'Bony Beetle' },
  0x32: { displayName: 'Dry Bones (stays on ledge)' },
  0x33: { displayName: 'Fireball' },
  0x34: { displayName: 'Boss Fireball' },
  0x35: { displayName: 'Yoshi (green)' },
  0x36: { displayName: 'Unused (0x36)' },
  0x37: { displayName: 'Boo' },
  0x38: { displayName: 'Eerie' },
  0x39: { displayName: 'Eerie (wave motion)' },
  0x3a: { displayName: 'Urchin (fixed)' },
  0x3b: { displayName: 'Urchin (wall detect)' },
  0x3c: { displayName: 'Urchin (wall follow)' },
  0x3d: { displayName: 'Rip Van Fish' },
  0x3e: { displayName: 'P-Switch' },
  0x3f: { displayName: 'Para-Goomba' },
  0x40: { displayName: 'Para-Bomb' },
  0x41: { displayName: 'Dolphin (horizontal)' },
  0x42: { displayName: 'Dolphin 2 (horizontal)' },
  0x43: { displayName: 'Dolphin (vertical)' },
  0x44: { displayName: 'Torpedo Ted' },
  0x45: { displayName: 'Directional Coins' },
  0x46: { displayName: "Diggin' Chuck" },
  0x47: { displayName: 'Fish (swimming/jumping)' },
  0x48: { displayName: "Diggin' Chuck's Rock" },
  0x49: { displayName: 'Growing/Shrinking Pipe' },
  0x4a: { displayName: 'Goal Sphere' },
  0x4b: { displayName: 'Pipe Lakitu' },
  0x4c: { displayName: 'Exploding Block' },
  0x4d: { displayName: 'Monty Mole (ground)' },
  0x4e: { displayName: 'Monty Mole (ledge)' },
  0x4f: { displayName: 'Piranha Plant (jumping)' },
  0x50: { displayName: 'Piranha Plant (jumping, fire)' },
  0x51: { displayName: 'Ninji' },
  0x52: { displayName: 'Moving Ledge (ghost house)' },
  0x53: { displayName: 'Throw Block' },
  // Platforms (0x54-0x68)
  0x54: { displayName: 'Climbing Net Door' },
  0x55: { displayName: 'Checkerboard Platform (horizontal)' },
  0x56: { displayName: 'Flying Rock Platform (horizontal)' },
  0x57: { displayName: 'Checkerboard Platform (vertical)' },
  0x58: { displayName: 'Flying Rock Platform (vertical)' },
  0x59: { displayName: 'Turn Block Bridge (H+V)' },
  0x5a: { displayName: 'Turn Block Bridge (horizontal)' },
  0x5b: { displayName: 'Brown Platform (floating)' },
  0x5c: { displayName: 'Checkerboard Platform (falling)' },
  0x5d: { displayName: 'Orange Platform (floating)' },
  0x5e: { displayName: 'Orange Platform (endless)' },
  0x5f: { displayName: 'Brown Platform on Chain' },
  0x60: { displayName: 'Switch Palace Switch' },
  0x61: { displayName: 'Floating Skull' },
  0x62: { displayName: 'Brown Platform (line-guided)' },
  0x63: { displayName: 'Checker Platform (line-guided)' },
  0x64: { displayName: 'Rope Mechanism (line-guided)' },
  0x65: { displayName: 'Chainsaw (line-guided)' },
  0x66: { displayName: 'Chainsaw Upside-Down (line-guided)' },
  0x67: { displayName: 'Grinder (line-guided)' },
  0x68: { displayName: 'Fuzzball (line-guided)' },
  0x69: { displayName: 'Unused (0x69)' },
  // Objects and power-ups (0x6A-0x90)
  0x6a: { displayName: 'Coin Cloud' },
  0x6b: { displayName: 'Springboard (left wall)' },
  0x6c: { displayName: 'Springboard (right wall)' },
  0x6d: { displayName: 'Invisible Solid Block' },
  0x6e: { displayName: 'Dino Rhino' },
  0x6f: { displayName: 'Dino Torch' },
  0x70: { displayName: 'Pokey' },
  0x71: { displayName: 'Super Koopa (red cape, straight)' },
  0x72: { displayName: 'Super Koopa (yellow cape, straight)' },
  0x73: { displayName: 'Super Koopa (yellow cape, swooping)' },
  0x74: { displayName: 'Mushroom' },
  0x75: { displayName: 'Fire Flower' },
  0x76: { displayName: 'Star' },
  0x77: { displayName: 'Cape Feather' },
  0x78: { displayName: '1-Up Mushroom' },
  0x79: { displayName: 'Growing Vine' },
  0x7a: { displayName: 'Firework' },
  0x7b: { displayName: 'Goal Tape' },
  0x7c: { displayName: 'Princess Peach' },
  0x7d: { displayName: 'Balloon' },
  0x7e: { displayName: 'Flying Red Coin' },
  0x7f: { displayName: 'Flying 1-Up' },
  0x80: { displayName: 'Key' },
  0x81: { displayName: 'Changing Item Block' },
  0x82: { displayName: 'Bonus Game Sprite' },
  0x83: { displayName: 'Flying ? Block (left)' },
  0x84: { displayName: 'Flying ? Block' },
  0x85: { displayName: 'Unused (0x85)' },
  0x86: { displayName: 'Wiggler' },
  0x87: { displayName: "Lakitu's Cloud" },
  0x88: { displayName: 'Winged Cage (unused)' },
  0x89: { displayName: 'Layer 3 Smash' },
  0x8a: { displayName: "Yoshi's House Bird" },
  0x8b: { displayName: "Yoshi's House Smoke" },
  0x8c: { displayName: 'Side Exit' },
  0x8d: { displayName: 'Ghost House Exit' },
  0x8e: { displayName: 'Invisible Warp Block' },
  0x8f: { displayName: 'Scale Platforms' },
  0x90: { displayName: 'Green Gas Bubble' },
  // Chucks and bosses (0x91-0xC8)
  0x91: { displayName: "Chargin' Chuck" },
  0x92: { displayName: "Splittin' Chuck" },
  0x93: { displayName: "Bouncin' Chuck" },
  0x94: { displayName: "Whistlin' Chuck" },
  0x95: { displayName: "Clappin' Chuck" },
  0x96: { displayName: "Chargin' Chuck (clone, unused)" },
  0x97: { displayName: "Puntin' Chuck" },
  0x98: { displayName: "Pitchin' Chuck" },
  0x99: { displayName: 'Volcano Lotus' },
  0x9a: { displayName: 'Sumo Brother' },
  0x9b: { displayName: 'Hammer Brother' },
  0x9c: { displayName: 'Hammer Brother Block' },
  0x9d: { displayName: 'Bubble (with sprite)' },
  0x9e: { displayName: 'Ball and Chain' },
  0x9f: { displayName: 'Banzai Bill' },
  0xa0: { displayName: 'Bowser Scene Activator' },
  0xa1: { displayName: "Bowser's Bowling Ball" },
  0xa2: { displayName: 'MechaKoopa' },
  0xa3: { displayName: 'Grey Platform on Chain' },
  0xa4: { displayName: 'Floating Spike Ball' },
  0xa5: { displayName: 'Sparky (ground-guided)' },
  0xa6: { displayName: 'HotHead (ground-guided)' },
  0xa7: { displayName: "Iggy's Ball" },
  0xa8: { displayName: 'Blargg' },
  0xa9: { displayName: 'Reznor' },
  0xaa: { displayName: 'Fishbone' },
  0xab: { displayName: 'Rex' },
  0xac: { displayName: 'Wooden Spike (down-first)' },
  0xad: { displayName: 'Wooden Spike (up-first)' },
  0xae: { displayName: "Fishin' Boo" },
  0xaf: { displayName: 'Boo Block' },
  0xb0: { displayName: 'Boo Buddies (reflecting)' },
  0xb1: { displayName: 'Creating/Eating Block' },
  0xb2: { displayName: 'Falling Spike' },
  0xb3: { displayName: 'Bowser Statue Fireball' },
  0xb4: { displayName: 'Grinder' },
  0xb5: { displayName: 'Sinking Fireball' },
  0xb6: { displayName: 'Reflecting Fireball' },
  0xb7: { displayName: 'Carrot Top Lift (upper right)' },
  0xb8: { displayName: 'Carrot Top Lift (upper left)' },
  0xb9: { displayName: 'Info Box' },
  0xba: { displayName: 'Timed Lift' },
  0xbb: { displayName: 'Grey Castle Block' },
  0xbc: { displayName: 'Bowser Statue' },
  0xbd: { displayName: 'Sliding Koopa (no shell)' },
  0xbe: { displayName: 'Swooper Bat' },
  0xbf: { displayName: 'Mega Mole' },
  0xc0: { displayName: 'Grey Lava Platform' },
  0xc1: { displayName: 'Flying Grey Turn Blocks' },
  0xc2: { displayName: 'Blurp Fish' },
  0xc3: { displayName: 'Porcu-Puffer Fish' },
  0xc4: { displayName: 'Grey Falling Platform' },
  0xc5: { displayName: 'Big Boo Boss' },
  0xc6: { displayName: 'Spotlight (dark room)' },
  0xc7: { displayName: 'Invisible Mushroom' },
  0xc8: { displayName: 'Light Switch Block' },
  // Generators and scrollers (0xC9+)
  0xc9: { displayName: 'Eerie Generator', isGenerator: true, spawns: 0x38 },
  0xca: { displayName: 'Para-Enemy Generator', isGenerator: true },
  0xcb: { displayName: 'Pipe Chomp Generator', isGenerator: true },
  0xcc: { displayName: 'Pipe Piranha Generator', isGenerator: true },
  0xcd: { displayName: 'Short Pipe Piranha Generator', isGenerator: true },
  0xce: { displayName: 'Jumping Piranha Generator', isGenerator: true },
  0xcf: { displayName: 'Jumping Fire Piranha Generator', isGenerator: true },
  0xd0: { displayName: 'Swimming Fish Generator', isGenerator: true },
  0xd1: { displayName: 'Surface Fish Generator', isGenerator: true },
  0xd2: { displayName: 'Vertical Fish Generator', isGenerator: true },
  0xd3: { displayName: 'Bullet Bill Shooter', isGenerator: true, spawns: 0x1c },
  0xd4: { displayName: 'Dolphin Generator', isGenerator: true, spawns: 0x41 },
  0xd5: { displayName: 'Lakitu Generator', isGenerator: true, spawns: 0x1e },
  0xd6: { displayName: 'Red Koopa Generator', isGenerator: true },
  0xd7: { displayName: 'Shell Generator', isGenerator: true },
  0xd8: { displayName: 'Bob-omb Generator', isGenerator: true },
  0xd9: { displayName: 'Boo Generator', isGenerator: true, spawns: 0x37 },
  // Shells (0xDA-0xDD, aliases to Koopa IDs 0x04-0x07)
  0xda: { displayName: 'Green Koopa Shell' },
  0xdb: { displayName: 'Red Koopa Shell' },
  0xdc: { displayName: 'Blue Koopa Shell' },
  0xdd: { displayName: 'Yellow Koopa Shell' },
  // Scroll controllers (0xDE-0xE7, no visible sprite)
  0xde: { displayName: 'Scroll Stop' },
  0xdf: { displayName: 'Scroll Stop (no Yoshi)' },
  0xe0: { displayName: 'Sprite Buoyancy' },
  0xe1: { displayName: 'Enable Lava Splash' },
  0xe2: { displayName: 'Enable Smoke Puffs' },
  0xe3: { displayName: 'Disable Scroll (vertical)' },
  0xe4: { displayName: 'Disable Scroll (horizontal)' },
  0xe5: { displayName: 'Disable All Scroll' },
  0xe6: { displayName: 'Autoscroll (slow)' },
  0xe7: { displayName: 'Autoscroll (fast)' },
}

export function getSpriteMetadata(id: number): SpriteMetadata | undefined {
  return SPRITE_METADATA[id]
}
